# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Account service CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
            
    - name: Build application
      run: mvn clean install

    - name: Test application
      run: mvn test
      
    - name: Analyze application
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TAndrian_we-go-jim

    - name: Check Quality Gate status
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      run: |
          STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=TAndrian_we-go-jim" -u $SONAR_TOKEN:)
          echo "Quality Gate status: $STATUS"
          if [[ "$STATUS" != *"\"status\":\"OK\""* ]]; then
            echo "Quality Gate failed"
            exit 1
          else
            echo "Quality Gate passed"
          fi

    - name: Build Docker image
      run: |
          docker build -t account_service_light .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push account_service_light

    - name: Deploy
      run: |
          # Ici tu peux ajouter les commandes pour déployer ton application
          echo "Déploiement en cours..."
